/**
 * ResponseDirective: the structured contract between orchestration and text generation.
 *
 * ┌──────────────────────────────────────────────────────────────────────┐
 * │  TEXT CATEGORY SEPARATION                                           │
 * │                                                                     │
 * │  1. ORCHESTRATION TEXT (deterministic, backend-owned)                │
 * │     - goal, constraints, missing_fields, known_data                 │
 * │     - These INSTRUCT the LLM what to communicate.                   │
 * │     - They are NOT shown to the patient.                            │
 * │                                                                     │
 * │  2. KNOWLEDGE TEXT (RAG-retrieved, clinic-owned)                     │
 * │     - Service descriptions, clinic info, policies.                  │
 * │     - Comes from KnowledgeDocument table, NOT hardcoded.            │
 * │     - Passed as facts for the LLM to paraphrase.                   │
 * │                                                                     │
 * │  3. TOOL RESULT TEXT (structured data from business operations)      │
 * │     - Slot times, appointment details, professional names.          │
 * │     - Always factual, never invented by the LLM.                   │
 * │                                                                     │
 * │  4. PATIENT-FACING TEXT (dynamically generated by LLM)              │
 * │     - The LLM produces reply_text from the above inputs.           │
 * │     - No hardcoded templates. No fixed phrasing.                   │
 * │     - Tone, style, and language flow are the LLM's responsibility. │
 * └──────────────────────────────────────────────────────────────────────┘
 */

export type ResponseDirective = {
  /** What the assistant must accomplish in this reply (e.g., "greet_patient", "ask_missing_field:full_name", "offer_available_slots") */
  goal: string;

  /** The detected/effective intent */
  intent: string;

  /** Facts the LLM MUST include in the response. Order matters — first fact is most important. */
  facts: string[];

  /** Hard constraints the LLM MUST obey (e.g., "do NOT confirm any appointment", "do NOT greet again"). */
  constraints: string[];

  /** Data already collected from the patient */
  known_data: Record<string, string>;

  /** Fields still required from the patient. If non-empty, the LLM should ask for the FIRST one only. */
  missing_fields: string[];

  /** Results from tool/use-case execution (slot times, appointment details, etc.) */
  tool_results?: Record<string, unknown>;

  /** Clinic display name */
  clinic_name: string;

  /** Tone setting (e.g., "warm_professional") */
  tone: string;

  /** Bot personality name */
  bot_name: string;

  /** The user's original message */
  patient_message: string;

  /** Whether this is the first message in the conversation */
  is_first_turn: boolean;

  /** Current date/time in ISO format for temporal context */
  now_iso?: string;

  /** Detected conversational signals */
  signals?: {
    has_greeting?: boolean;
    greeting_type?: string | null;
    has_concern?: boolean;
    has_service_mention?: boolean;
    mentioned_service_name?: string | null;
  };
};
